---
- hosts: localhost
  connection: local

  tasks:
  - name: Create EC2 instances
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "deepu"
      instance_type: t2.micro
      security_group: default
      region: us-east-2
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
      tags:
        environment: "{{ item.name }}"
    loop:
      - { image: "ami-0ea3c35c5c3284d82", name: "manage-node-1" }
      - { image: "ami-0ea3c35c5c3284d82", name: "manage-node-2" }
      - { image: "ami-09da212cf18033880", name: "manage-node-3" }
